name: gestions_des_depense_des_enfants
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  get: ^4.6.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.0.8
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/sen/Sen-Regular.ttf
        - asset: assets/fonts/sen/Sen-Medium.ttf
          weight: 700
        - asset: assets/fonts/sen/Sen-Bold.ttf
          weight: 900

  assets:
    - assets/
    - assets/splash/
    - assets/welcome/
    - assets/auth/
